apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: eatcore
  name: eatcore
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: eatcore
  template:
    metadata:
      labels:
        k8s-app: eatcore
    spec:
      containers:
        - image: ghcr.io/jsleeio/eatcore:v0.3.1
          imagePullPolicy: IfNotPresent
          name: eatcore
          args:
# exit if maximum increments reached successfully
          - '-x'
# every 60 seconds
          - '-i 60'
# allocate and touch 500MiB memory
          - '-s 500'
# up to 100 times
          - '-n 100'
